export const API_ENDPOINTS = {
  LOGIN: "/auth/customer/login",
  REGISTER: "/auth/customer/register",
  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/shop/categories/get-categories",
  CATEGORY: "/shop/categories/set-category",
  FEATURED_CATEGORIES: "/shop/categories/featured-categories",
  COLLECTIONS: "/collections.json",
  BRANDS: "/brands.json",
  PRODUCTS: "/shop/products/get-products",
  SET_PRODUCT: "/shop/products/set-product",
  FEATURED_PRODUCTS: "/shop/products/featured-products",
  TOP_SELLER_PRODUCTS: "/shop/products/featured-products",
  ON_SELLING_PRODUCTS: "/shop/products/featured-products",
  PRODUCT: "/shop/products/get-product-by-id",
  RELATED_PRODUCTS: "/shop/products/featured-products",
  BEST_SELLER_PRODUCTS: "/shop/products/featured-products",
  NEW_ARRIVAL_PRODUCTS: "/shop/products/featured-products",
  FLASH_SALE_PRODUCTS: "/shop/products/featured-products",
  SEARCH: "/search.json",
  ORDERS: "/orders.json",
  ORDER: "/order.json",
  CHECK_OUT: "/order/payment/checkout-sessions",
};
